workspace: OnlinePaymentsExample.xcworkspace
schemes:
- OnlinePaymentsExample
targets:
- OnlinePaymentsExample
clean_build: true
build_arguments:
- -destination
- platform="iOS Simulator,name=iPhone 13,OS=15.5"

